### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by lahmatiy** [csstree/csstree#29]
- [x] move !important from `Value` to `Declaration`
- [x] `Braces` -> `Parentheses`
- [x] `Ruleset` -> `Rule`
- [x] drop `Unknown`
- [x] replace `Identifier` -> `Type`/`Universal` selector
- [x] `FunctionalPseudo` -> `PseudoClass`
- [x] fix attribute name parsing
- [x] add `Brackets` since `CSS Grid Layout` [introduces it](https://drafts.csswg.org/css-grid/#track-sizing)
- [x] at-rule inside block (#24)
- [x] `of` clause for `nth-child`/`nth-last-child` e.g. `nth-child(.. of <Selector>)`
- [x] check number is integer for
  - [x] `UnicodeRange`
  - [x] `Hash`
  - [x] `Nth` (an+b)
- [x] natural traversal order for `walk()` (current behaviour should be implemented as `walkUp()`)
- [x] :matches() (#28)
- [x] :has()
- [x] [::slotted()](https://github.com/css/csso/issues/319)
- [x] rename `sequence` -> `children` for node types
- [x] end line/column in node.info
- [x] rename `Selector` -> `SelectorList`, `SimpleSelector` -> `Selector`
- [x] fix `Block` positions (should include `{}`)
- [x] fix positions for `Selector`/`SimpleSelector` to not include ws
- [x] rename `StyleSheet` inside at-rule to `Block` (when at-rule will be allowed inside block)
- [x] add `loc` to `Nth`
- [x] use balanced raw consumer for custom properties
- [x] `DeclarationList` instead of `Block` and add `declarationList` context (for `<element style="">` context)
- [x] `Atrule.expression` should be null when no expression
- [x] split parser into modules (one per node type)
- [x] custom parsers for well-known at-rule expressions
- [x] add `Selector` suffix for `Id`, `Class`, `Attribute`, `Type`, `PseudoClass` and `PseudoElement`
- [x] options to parse `Value`, `Selector` and `AtruleExpression` as balanced `Raw` (`parseValue`, `parseSelector`, `parseAtruleExpression`)
- [x] option to parse custom property value/fallback as regular value (`parseCustomProperty`)
- [x] drop `Progid`
- [x] rename `Space` to `WhiteSpace`
- [x] rename `Hash` to `HexColor`
- [x] parse unknown parts of `Value` as balanced `Raw`

Under consideration:
- `Percentage` -> `Dimension`
- ~multiple `Value` (no parts comma operator, but list of Value)~
  > more convenient to work with Value in current form
- ~explicit descendant combinator `>>`~
  > until any browser support
- ~Column combinator `||`~
  > until any browser support
- convert name node to property in `Attribute`
  - q: where to store location?
- namespaces for `Type`/`Universal`/`Attribute` (special case for :matches)
  - q: should we need store it separately?
- ~rename `loc` -> `meta` (to store formatting info too)~
- ~rename `Block` -> `{}-block`, `Parenthesis` -> `()-block`, `Brackets` -> `[]-block` according to [CSS Syntax Module Level 3](https://www.w3.org/TR/css-syntax-3)~ that's for tokens not ast node
- ~should `SelectorList` to be omitted when have a single selector?~
- ~replace `Rule.block` to `Rule.children` and `Atrule.block` to `Atrule.children`~
  > bad idea, since block includes `{}` now
- rename `positions` parse option to `loc`
- store formatting info somehow
- ~allow percent in @keyframes selectors only (from/to/percent)~ should restrict by lexer not parser
- ~better name for `parse*` options~ looks ok for now
